### ISSUE TITLE
.\CrashLogger.dll flagged infected

### ISSUE THREAD

**Issue by tamadNaBrowNie** [yvileapsis/yUI-NVSE#10]
I do not know why but bitdefender has flagged the file as infected. the log is as follows: "vse\plugins\CrashLogger.dll is infected with Gen:Variant.Lazy.393374 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean." seems to be a false positive.

**Comment by yvileapsis** [comment]
Apparently was tied to me using static linking instead of dynamic linking. Seems to be fixed now.
